import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Manipuri AI" },
      { name: "description", content: "The terms that govern your use of Manipuri AI." },
      { property: "og:title", content: "Terms of Service — Manipuri AI" },
      { property: "og:description", content: "The terms that govern your use of Manipuri AI." },
      { property: "og:url", content: "https://manipuriai.online/terms" },
    ],
    links: [{ rel: "canonical", href: "https://manipuriai.online/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen aurora-bg">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
          <ArrowLeft className="h-4 w-4" /> Back to home
        </Link>
        <h1 className="mt-6 text-4xl font-bold tracking-tight" style={{ fontFamily: "var(--font-serif)", color: "var(--gold)" }}>
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: July 18, 2026</p>

        <div className="mt-8 max-w-none space-y-6 text-sm leading-relaxed text-foreground/90">
          <section>
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance</h2>
            <p>By using Manipuri AI you agree to these terms. If you don't agree, please don't use the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">2. The service</h2>
            <p>Manipuri AI provides an AI chatbot fluent in Meiteilon (Manipuri) and English, along with optional voice and image-generation features. Responses are generated by AI and may be inaccurate — do not rely on them for medical, legal, or financial decisions.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">3. Accounts</h2>
            <p>You must be 13 or older. You are responsible for keeping your login secure and for activity under your account. One person per account.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">4. Acceptable use</h2>
            <p>Don't use Manipuri AI to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>generate illegal, hateful, sexual (involving minors), or violent content;</li>
              <li>harass, impersonate, or defame anyone;</li>
              <li>attempt to reverse-engineer, scrape, or overwhelm the service;</li>
              <li>evade rate limits or resell responses without permission.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">5. Payments & refunds</h2>
            <p>Paid plans (Pro ₹99/month, Max ₹399/month) are billed in advance via Razorpay. Because AI generation costs are incurred immediately, subscriptions are non-refundable once the billing period starts. You may cancel anytime to prevent renewal.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">6. Content</h2>
            <p>You own the prompts you write. You grant us a limited license to process them to generate responses and to store your chat history. AI-generated output is provided as-is with no ownership claim from us; use it responsibly.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">7. Termination</h2>
            <p>We may suspend or terminate accounts that violate these terms. You can delete your account at any time.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">8. Disclaimer</h2>
            <p>The service is provided "as is" without warranties. To the maximum extent allowed by law, we are not liable for indirect or consequential damages arising from use of Manipuri AI.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">9. Governing law</h2>
            <p>These terms are governed by the laws of India. Disputes will be handled in the courts of Manipur, India.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">10. Contact</h2>
            <p>Reach out on Telegram: <a className="underline" href="https://t.me/MrLeona">@MrLeona</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
